import { useEffect, useMemo, useRef, useState } from "react";
import { api, type ActionItem, type Analysis, type Brief, type Customer, type Dashboard, type Meeting, type Opportunity } from "./api";

type Page = "overview" | "customers" | "brief" | "voice" | "tasks" | "ask";
type Toast = { kind: "success" | "error"; message: string } | null;

const nav: { id: Page; icon: string; label: string }[] = [
  { id: "overview", icon: "⌂", label: "Overview" }, { id: "customers", icon: "◉", label: "Customers" },
  { id: "voice", icon: "⌁", label: "Voice meeting" }, { id: "tasks", icon: "✓", label: "Action items" },
];

const money = (value?: string, currency = "INR") => new Intl.NumberFormat("en-IN", { style: "currency", currency, notation: "compact", maximumFractionDigits: 1 }).format(Number(value || 0));
const humanDate = (value?: string) => value ? new Intl.DateTimeFormat("en-IN", { month: "short", day: "numeric" }).format(new Date(value)) : "No date";
const todayISO = () => new Date().toISOString().slice(0, 10);

function Badge({ children, tone = "slate" }: { children: React.ReactNode; tone?: "slate" | "green" | "amber" | "rose" | "violet" }) { return <span className={`badge badge-${tone}`}>{children}</span>; }
function Spinner() { return <span className="spinner" aria-label="Loading" />; }

export default function App() {
  const [page, setPage] = useState<Page>("overview");
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [dashboard, setDashboard] = useState<Dashboard | null>(null);
  const [selected, setSelected] = useState<Customer | null>(null);
  const [toast, setToast] = useState<Toast>(null);
  const notify = (kind: "success" | "error", message: string) => { setToast({ kind, message }); window.setTimeout(() => setToast(null), 4500); };
  const refresh = async () => {
    try { const [customerData, dashboardData] = await Promise.all([api.customers(), api.dashboard()]); setCustomers(customerData); setDashboard(dashboardData); setSelected((current) => current ? customerData.find(c => c.id === current.id) || null : customerData[0] || null); }
    catch (error) { notify("error", error instanceof Error ? error.message : "Could not load the CRM."); }
  };
  useEffect(() => { void refresh(); }, []);
  const chooseCustomer = (customer: Customer, destination: Page = "customers") => { setSelected(customer); setPage(destination); };

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-orb">S</span><span>salespilot</span></div>
      <div className="workspace"><span className="workspace-dot" /> Northstar sales <span className="chevron">⌄</span></div>
      <nav>{nav.map(item => <button key={item.id} className={page === item.id ? "nav-item active" : "nav-item"} onClick={() => setPage(item.id)}><span>{item.icon}</span>{item.label}</button>)}</nav>
      <div className="sidebar-bottom">
        <button className={page === "ask" ? "ask-launch active" : "ask-launch"} onClick={() => setPage("ask")}><span className="spark">✦</span><span><small>AI assistant</small>Ask SalesPilot</span></button>
        <div className="user-chip"><span className="avatar">TM</span><span><strong>Tirtha Mehta</strong><small>Account executive</small></span><span>⋮</span></div>
      </div>
    </aside>
    <main className="main-content">
      <header className="topbar"><div className="mobile-brand">salespilot</div><div className="top-actions"><button className="icon-button" aria-label="Notifications">♧<i /></button><button className="help">?</button></div></header>
      {page === "overview" && <Overview dashboard={dashboard} customers={customers} onCustomer={chooseCustomer} onPage={setPage} />}
      {page === "customers" && <CustomersPage customers={customers} selected={selected} onCustomer={chooseCustomer} onBrief={() => setPage("brief")} />}
      {page === "brief" && <BriefPage customer={selected} onBack={() => setPage("customers")} />}
      {page === "voice" && <VoicePage customers={customers} selected={selected} onSelect={setSelected} onDone={() => { void refresh(); setPage("customers"); }} notify={notify} />}
      {page === "tasks" && <TasksPage customers={customers} />}
      {page === "ask" && <AskPage />}
    </main>
    {toast && <div className={`toast ${toast.kind}`}><span>{toast.kind === "success" ? "✓" : "!"}</span>{toast.message}</div>}
  </div>;
}

function Overview({ dashboard, customers, onCustomer, onPage }: { dashboard: Dashboard | null; customers: Customer[]; onCustomer: (c: Customer, p?: Page) => void; onPage: (p: Page) => void }) {
  const customerFor = (id: number) => customers.find(c => c.id === id);
  const total = dashboard?.open_opportunities.reduce((sum, op) => sum + Number(op.value), 0) || 0;
  return <section className="page overview">
    <div className="eyebrow">MONDAY, SEPTEMBER 15</div><h1>Good morning, Tirtha <span>✦</span></h1><p className="lede">Here’s where your customer relationships need you today.</p>
    <div className="metric-grid">
      <Metric label="Follow-ups today" value={dashboard ? String(dashboard.today_follow_ups.length).padStart(2, "0") : "–"} sub="Keep momentum moving" accent="blue" />
      <Metric label="Overdue actions" value={dashboard ? String(dashboard.overdue_actions.length).padStart(2, "0") : "–"} sub="Need attention now" accent="coral" />
      <Metric label="Open pipeline" value={dashboard ? money(String(total)) : "–"} sub={`${dashboard?.open_opportunities.length || 0} active opportunities`} accent="violet" />
    </div>
    <div className="dashboard-grid">
      <article className="panel upcoming-panel"><div className="panel-title"><div><span className="eyebrow">TODAY</span><h2>Follow-up radar</h2></div><button onClick={() => onPage("tasks")}>View all <span>→</span></button></div>
        {!dashboard ? <div className="panel-loading"><Spinner /></div> : <div className="follow-list">{[...dashboard.today_follow_ups, ...dashboard.overdue_actions].slice(0, 4).map((item, index) => { const customer = customerFor(item.customer_id); return <button className="follow-row" key={item.id} onClick={() => customer && onCustomer(customer, "customers")}><span className={`priority-dot p${index % 3}`} /><span className="follow-copy"><strong>{item.task}</strong><small>{customer?.name || "Customer"} · due {humanDate(item.due_date)}</small></span><Badge tone={item.priority === "HIGH" ? "rose" : "amber"}>{item.priority.toLowerCase()}</Badge><span className="row-arrow">→</span></button>; })}{!dashboard.today_follow_ups.length && !dashboard.overdue_actions.length && <div className="empty">Nothing is due today. Nice work.</div>}</div>}
      </article>
      <article className="panel prepare-panel"><div className="panel-title"><div><span className="eyebrow">NEXT UP</span><h2>Customer intelligence</h2></div><span className="live-dot">Live CRM</span></div>
        <p>Go into every conversation knowing what matters most.</p><div className="prepare-stack">{customers.slice(0, 3).map((customer, index) => <div className="prepare-card" key={customer.id}><div className={`company-mark mark-${index}`}>{customer.name.slice(0, 1)}</div><div><strong>{customer.name}</strong><small>{customer.industry}</small></div><button onClick={() => onCustomer(customer, "brief")}>Prepare <span>↗</span></button></div>)}</div>
      </article>
    </div>
    <article className="panel opportunity-panel"><div className="panel-title"><div><span className="eyebrow">PIPELINE</span><h2>Open opportunities</h2></div><button onClick={() => onPage("customers")}>All customers <span>→</span></button></div><div className="opportunity-table"><div className="opportunity-head"><span>Customer</span><span>Stage</span><span>Value</span><span>Confidence</span></div>{dashboard?.open_opportunities.slice(0, 4).map(op => <OpportunityRow key={op.id} opportunity={op} customer={customerFor(op.customer_id)} onClick={() => { const c = customerFor(op.customer_id); if (c) onCustomer(c, "customers"); }} />) || <div className="panel-loading"><Spinner /></div>}</div></article>
  </section>;
}

function Metric({ label, value, sub, accent }: { label: string; value: string; sub: string; accent: string }) { return <article className={`metric metric-${accent}`}><span className="metric-label">{label}</span><strong>{value}</strong><small>{sub}</small><span className="metric-shape" /></article>; }
function OpportunityRow({ opportunity, customer, onClick }: { opportunity: Opportunity; customer?: Customer; onClick: () => void }) { return <button className="opportunity-row" onClick={onClick}><span className="customer-cell"><span className="tiny-avatar">{customer?.name.slice(0, 1) || "?"}</span><span><strong>{customer?.name || "Customer"}</strong><small>{opportunity.name}</small></span></span><span><Badge tone={opportunity.stage === "NEGOTIATION" ? "violet" : "amber"}>{opportunity.stage.toLowerCase()}</Badge></span><strong>{money(opportunity.value, opportunity.currency)}</strong><span className="confidence"><i><b style={{ width: `${opportunity.probability}%` }} /></i>{opportunity.probability}%</span></button>; }

function CustomersPage({ customers, selected, onCustomer, onBrief }: { customers: Customer[]; selected: Customer | null; onCustomer: (c: Customer, p?: Page) => void; onBrief: () => void }) {
  const [query, setQuery] = useState(""); const filtered = customers.filter(c => c.name.toLowerCase().includes(query.toLowerCase()));
  return <section className="page customers-page"><div className="section-header"><div><span className="eyebrow">CRM</span><h1>Customers</h1><p className="lede">Everything your team knows, in one calm workspace.</p></div><button className="primary" disabled={!selected && !customers[0]} onClick={() => { const customer = selected || customers[0]; if (customer) onCustomer(customer, "voice"); }}>⌁ Record a meeting</button></div>
    <div className="customer-layout"><article className="panel customer-list"><div className="search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search customers" /></div>{filtered.map(customer => <button key={customer.id} onClick={() => onCustomer(customer)} className={`customer-list-row ${selected?.id === customer.id ? "selected" : ""}`}><span className="company-initial">{customer.name[0]}</span><span><strong>{customer.name}</strong><small>{customer.industry} · {customer.location}</small></span><span>›</span></button>)}</article>
      {selected ? <CustomerDetails customer={selected} onBrief={onBrief} /> : <div className="panel empty">Select a customer to see their account.</div>}</div>
  </section>;
}

function CustomerDetails({ customer, onBrief }: { customer: Customer; onBrief: () => void }) {
  const [data, setData] = useState<{meetings: Meeting[]; opportunities: Opportunity[]; action_items: ActionItem[]} | null>(null);
  const [loading, setLoading] = useState(false);
  useEffect(() => { setLoading(true); void api.history(customer.id).then(result => setData(result)).catch(() => setData(null)).finally(() => setLoading(false)); }, [customer.id]);
  const primaryContact = customer.contacts?.[0]; const total = data?.opportunities.reduce((sum, item) => sum + Number(item.value), 0) || 0;
  return <article className="panel customer-detail">{loading ? <div className="detail-loader"><Spinner /></div> : <><div className="detail-hero"><span className="large-initial">{customer.name[0]}</span><div><span className="eyebrow">CUSTOMER PROFILE</span><h2>{customer.name}</h2><p>{customer.industry} · {customer.location}</p></div><button className="primary" onClick={onBrief}>✦ Prepare me</button></div>
    <div className="profile-stats"><div><small>Open pipeline</small><strong>{money(String(total))}</strong></div><div><small>Active opportunities</small><strong>{data?.opportunities.length || 0}</strong></div><div><small>Open actions</small><strong>{data?.action_items.filter(a => a.status !== "DONE").length || 0}</strong></div></div>
    <div className="detail-columns"><div><SectionTitle title="Primary contact" /><div className="contact-card"><span className="avatar warm">{primaryContact?.name.split(" ").map(n => n[0]).join("") || "–"}</span><span><strong>{primaryContact?.name || "No contact recorded"}</strong><small>{primaryContact?.designation || ""}</small><small>{primaryContact?.email || ""}</small></span></div><SectionTitle title="Recent conversations" /><div className="timeline">{data?.meetings.slice(0, 3).map(meeting => <div key={meeting.id}><span /><p><small>{humanDate(meeting.meeting_date)}</small>{meeting.summary}</p></div>)}{!data?.meetings.length && <p className="empty">No meetings recorded yet.</p>}</div></div>
      <div><SectionTitle title="Open actions" /><div className="mini-list">{data?.action_items.filter(a => a.status !== "DONE").slice(0, 4).map(a => <div key={a.id}><span className="check-ring" /><p>{a.task}<small>Due {humanDate(a.due_date)}</small></p><Badge tone={a.priority === "HIGH" ? "rose" : "amber"}>{a.priority.toLowerCase()}</Badge></div>) || <div className="empty">No actions.</div>}</div><SectionTitle title="Competitive landscape" /><div className="competitors">{data?.opportunities.map(o => o.competitor).filter(Boolean).map((name, index) => <span key={`${name}${index}`}>⚑ {name}</span>)}{!data?.opportunities.some(o => o.competitor) && <span>Not recorded</span>}</div></div></div></>}</article>;
}
function SectionTitle({ title }: { title: string }) { return <h3 className="section-title">{title}</h3>; }

function BriefPage({ customer, onBack }: { customer: Customer | null; onBack: () => void }) {
  const [brief, setBrief] = useState<Brief | null>(null); const [error, setError] = useState("");
  useEffect(() => { if (!customer) return; setBrief(null); setError(""); void api.brief(customer.id).then(setBrief).catch(e => setError(e.message)); }, [customer?.id]);
  if (!customer) return <section className="page blank-page"><h1>Choose a customer first</h1><button className="primary" onClick={onBack}>View customers</button></section>;
  if (!brief && !error) return <section className="page brief-loading"><div className="brief-pulse">✦</div><h1>Preparing your brief</h1><p>Connecting the dots across {customer.name}’s account history…</p><Spinner /></section>;
  if (error) return <section className="page blank-page"><h1>We couldn’t build this brief.</h1><p>{error}</p><button className="secondary" onClick={onBack}>Back to customers</button></section>;
  return <section className="page brief-page"><button className="back" onClick={onBack}>← All customers</button><div className="brief-header"><div><span className="eyebrow">AI MEETING BRIEF · {brief?.source === "local_demo" ? "CRM-GROUNDED" : "LIVE"}</span><h1>{customer.name}</h1><p>{brief?.customer_overview}</p></div><div className="brief-contact"><span className="avatar warm">{customer.contacts?.[0]?.name.split(" ").map(x => x[0]).join("")}</span><span><small>YOUR CONTACT</small><strong>{customer.contacts?.[0]?.name || "Not recorded"}</strong><em>{customer.contacts?.[0]?.designation}</em></span></div></div>
    <div className="brief-hero"><span className="hero-glow" /><div><span className="eyebrow">✦ AI RECOMMENDATION</span><h2>{brief?.recommended_talking_points[0] || "Start by confirming the customer’s highest-priority outcome."}</h2><p>{brief?.relationship_summary}</p></div><span className="recommendation-mark">✦</span></div>
    <div className="brief-grid"><BriefCard title="Open opportunity" icon="↗"><div className="brief-lines">{brief?.open_opportunities.map(item => <p key={item}>{item}</p>) || <p>Not available</p>}</div></BriefCard><BriefCard title="Last discussions" icon="◌"><div className="brief-lines">{brief?.recent_discussions.map(item => <p key={item}>{item}</p>) || <p>No discussion recorded</p>}</div></BriefCard><BriefCard title="Customer pain points" icon="!" danger><BulletList values={brief?.pain_points || []} empty="No pain points recorded" /></BriefCard><BriefCard title="Competitive context" icon="⚑"><BulletList values={brief?.competitors || []} empty="No competitors recorded" /></BriefCard><BriefCard title="Outstanding actions" icon="✓"><BulletList values={brief?.outstanding_actions || []} empty="No outstanding actions" /></BriefCard><BriefCard title="Risks to navigate" icon="△" danger><BulletList values={brief?.risks || []} empty="No material risks recorded" /></BriefCard></div>
    <div className="questions-panel"><div><span className="eyebrow">GO DEEPER</span><h2>Questions worth asking</h2></div><ol>{brief?.recommended_questions.map(question => <li key={question}>{question}</li>)}</ol></div>
  </section>;
}
function BriefCard({ title, icon, children, danger }: { title: string; icon: string; children: React.ReactNode; danger?: boolean }) { return <article className={`brief-card ${danger ? "danger" : ""}`}><span className="brief-icon">{icon}</span><h3>{title}</h3>{children}</article>; }
function BulletList({ values, empty }: { values: string[]; empty: string }) { return values.length ? <ul className="brief-list">{values.map(value => <li key={value}>{value}</li>)}</ul> : <p className="muted">{empty}</p>; }

function VoicePage({ customers, selected, onSelect, onDone, notify }: { customers: Customer[]; selected: Customer | null; onSelect: (customer: Customer) => void; onDone: () => void; notify: (kind: "success" | "error", message: string) => void }) {
  const [phase, setPhase] = useState<"ready" | "recording" | "paused" | "processing" | "review">("ready"); const [seconds, setSeconds] = useState(0); const [transcript, setTranscript] = useState(""); const [analysis, setAnalysis] = useState<Analysis | null>(null); const [match, setMatch] = useState<{match_status: string; customer?: {id: number; name: string}; candidates: {id: number; name: string}[]} | null>(null); const [customerId, setCustomerId] = useState<number | "">(selected?.id || "");
  const recorder = useRef<MediaRecorder | null>(null); const chunks = useRef<Blob[]>([]);
  useEffect(() => { if (phase !== "recording") return; const timer = window.setInterval(() => setSeconds(value => value + 1), 1000); return () => window.clearInterval(timer); }, [phase]);
  const clock = `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;
  const analyze = async (value: string) => { setPhase("processing"); try { const result = await api.analyze(value); setAnalysis(result.analysis); setMatch(result.match); if (result.match.customer) setCustomerId(result.match.customer.id); setPhase("review"); } catch (error) { setPhase("ready"); notify("error", error instanceof Error ? error.message : "Could not analyze the meeting."); } };
  const start = async () => { try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const media = new MediaRecorder(stream); chunks.current = []; media.ondataavailable = e => { if (e.data.size) chunks.current.push(e.data); }; media.onstop = () => { stream.getTracks().forEach(track => track.stop()); const audio = new Blob(chunks.current, { type: media.mimeType || "audio/webm" }); void api.transcribe(audio).then(result => { setTranscript(result.transcript); return analyze(result.transcript); }).catch(error => { setPhase("ready"); notify("error", error instanceof Error ? error.message : "Transcription failed. You can paste the transcript instead."); }); }; recorder.current = media; media.start(); setSeconds(0); setPhase("recording"); } catch { notify("error", "Microphone access was not granted."); } };
  const stop = () => recorder.current?.state !== "inactive" && recorder.current?.stop();
  const togglePause = () => { if (!recorder.current) return; if (recorder.current.state === "recording") { recorder.current.pause(); setPhase("paused"); } else { recorder.current.resume(); setPhase("recording"); } };
  const save = async () => { if (!analysis || !customerId) return notify("error", "Choose the customer before saving."); const customer = customers.find(c => c.id === customerId); if (!customer) return; try { await api.confirm({ customer_id: customer.id, contact_id: customer.contacts?.[0]?.id ?? null, meeting_date: new Date().toISOString(), title: `Meeting with ${customer.name}`, transcript, analysis }); notify("success", "Meeting saved and action items created."); onDone(); } catch (error) { notify("error", error instanceof Error ? error.message : "Could not save the meeting."); } };
  return <section className="page voice-page"><div className="section-header"><div><span className="eyebrow">AFTER THE MEETING</span><h1>Tell SalesPilot what happened</h1><p className="lede">Record your notes, then review every detail before it touches the CRM.</p></div><div className="human-lock">♢ Human review required</div></div>
    {phase === "ready" && <div className="voice-layout"><article className="record-card"><div className="microphone">⌁</div><span className="eyebrow">READY WHEN YOU ARE</span><h2>Capture the conversation</h2><p>SalesPilot will transcribe your recording, extract the commitments, and wait for your approval.</p><button className="record-button" onClick={() => void start()}><span>●</span> Start recording</button><small>Your recording is sent securely to the backend for transcription.</small></article><article className="paste-card"><span className="eyebrow">OR START WITH TEXT</span><h3>Have notes already?</h3><textarea value={transcript} onChange={e => setTranscript(e.target.value)} placeholder="Paste or write a meeting recap…" /><button className="secondary" disabled={transcript.trim().length < 4} onClick={() => void analyze(transcript)}>Analyze notes <span>→</span></button></article></div>}
    {(phase === "recording" || phase === "paused") && <div className="recording-stage"><div className="recording-orbit"><span>●</span></div><span className="eyebrow">{phase === "paused" ? "PAUSED" : "RECORDING"}</span><h2>{clock}</h2><p>{phase === "paused" ? "Your recording is safe. Continue when you’re ready." : "Listening for your meeting notes…"}</p><div className="recording-controls"><button className="secondary" onClick={togglePause}>{phase === "paused" ? "▶ Resume" : "Ⅱ Pause"}</button><button className="stop-button" onClick={stop}>■ Stop & analyze</button></div></div>}
    {phase === "processing" && <div className="processing-stage"><div className="brief-pulse">✦</div><h2>Making sense of the meeting</h2><div className="process-lines"><p><span className="done">✓</span> Audio transcribed</p><p><Spinner /> Identifying customer and commitments</p><p><span>○</span> Drafting action items for your review</p></div></div>}
    {phase === "review" && analysis && <MeetingReview analysis={analysis} setAnalysis={setAnalysis} transcript={transcript} setTranscript={setTranscript} customers={customers} customerId={customerId} setCustomerId={setCustomerId} match={match} onSave={() => void save()} />}
  </section>;
}

function MeetingReview({ analysis, setAnalysis, transcript, setTranscript, customers, customerId, setCustomerId, match, onSave }: { analysis: Analysis; setAnalysis: (analysis: Analysis) => void; transcript: string; setTranscript: (value: string) => void; customers: Customer[]; customerId: number | ""; setCustomerId: (value: number | "") => void; match: {match_status: string; customer?: {id: number; name: string}; candidates: {id: number; name: string}[]} | null; onSave: () => void }) {
  const editActions = (index: number, task: string) => setAnalysis({ ...analysis, action_items: analysis.action_items.map((item, i) => i === index ? { ...item, task } : item) });
  return <div className="review-layout"><div className="review-title"><div><span className="eyebrow">HUMAN-IN-THE-LOOP</span><h2>Here’s what I understood</h2><p>Edit anything that needs your judgement. Nothing has been saved yet.</p></div><Badge tone={match?.match_status === "MATCHED" ? "green" : "amber"}>{match?.match_status === "MATCHED" ? "Customer matched" : "Choose customer"}</Badge></div><div className="review-grid"><article className="panel transcript-panel"><SectionTitle title="Transcript" /><textarea value={transcript} onChange={e => setTranscript(e.target.value)} /><div className="analysis-source">AI confidence: {Math.round(analysis.confidence.overall * 100)}% · Always review before saving</div></article><article className="panel analysis-panel"><SectionTitle title="Meeting analysis" /><label>Customer<select value={customerId} onChange={e => setCustomerId(e.target.value ? Number(e.target.value) : "")}><option value="">Select customer…</option>{(match?.match_status === "AMBIGUOUS" ? match.candidates : customers).map(customer => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></label>{match?.match_status === "AMBIGUOUS" && <p className="clarification">Multiple customers may match this transcript. Your selection is required.</p>}<label>Summary<textarea className="summary-input" value={analysis.summary || ""} onChange={e => setAnalysis({ ...analysis, summary: e.target.value })} /></label><div className="extraction-columns"><Extraction title="Requirements" values={analysis.requirements} /><Extraction title="Concerns" values={analysis.customer_concerns} /><Extraction title="Competitors" values={analysis.competitors} /></div><SectionTitle title="Action items" />{analysis.action_items.length ? <div className="editable-actions">{analysis.action_items.map((item, index) => <div key={`${item.task}${index}`}><span className="check-ring" /><input value={item.task} onChange={e => editActions(index, e.target.value)} /><input className="date" type="date" value={item.due_date || ""} onChange={e => setAnalysis({ ...analysis, action_items: analysis.action_items.map((a, i) => i === index ? { ...a, due_date: e.target.value || undefined } : a) })} /><Badge tone={item.priority === "HIGH" ? "rose" : "amber"}>{item.priority.toLowerCase()}</Badge></div>)}</div> : <p className="empty">No action items were explicitly found.</p>}<button className="primary save-button" disabled={!customerId} onClick={onSave}>✓ Confirm & save meeting</button></article></div></div>;
}
function Extraction({ title, values }: { title: string; values: string[] }) { return <div className="extraction"><small>{title}</small>{values.length ? values.map(value => <p key={value}>{value}</p>) : <em>Not mentioned</em>}</div>; }

function TasksPage({ customers }: { customers: Customer[] }) { const [items, setItems] = useState<ActionItem[] | null>(null); useEffect(() => { void api.actions().then(setItems).catch(() => setItems([])); }, []); const customer = (id: number) => customers.find(c => c.id === id)?.name || "Customer"; return <section className="page tasks-page"><span className="eyebrow">EXECUTION</span><h1>Action items</h1><p className="lede">Every customer commitment, visible and moving forward.</p><div className="task-columns"><TaskColumn title="Overdue" tone="rose" items={items?.filter(item => item.due_date && item.due_date < todayISO()) || []} customer={customer} /><TaskColumn title="Today" tone="amber" items={items?.filter(item => item.due_date === todayISO()) || []} customer={customer} /><TaskColumn title="Upcoming" tone="violet" items={items?.filter(item => !item.due_date || item.due_date > todayISO()) || []} customer={customer} /></div></section>; }
function TaskColumn({ title, tone, items, customer }: { title: string; tone: "rose" | "amber" | "violet"; items: ActionItem[]; customer: (id: number) => string }) { return <article className="task-column"><h2><span className={`column-dot ${tone}`} />{title}<small>{items.length}</small></h2>{items.map(item => <div className="task-card" key={item.id}><span className="check-ring" /><div><strong>{item.task}</strong><small>{customer(item.customer_id)} · {humanDate(item.due_date)}</small></div><Badge tone={item.priority === "HIGH" ? "rose" : "amber"}>{item.priority.toLowerCase()}</Badge></div>)}{!items.length && <div className="empty task-empty">No items here.</div>}</article>; }

function AskPage() { const [question, setQuestion] = useState(""); const [messages, setMessages] = useState<{role: "user" | "assistant"; content: string; sources?: string[]}[]>([{ role: "assistant", content: "I’m ready to help with the CRM. Ask about follow-ups, customers, recent meetings, or opportunity risk." }]); const [sending, setSending] = useState(false); const ask = async (value = question) => { if (!value.trim() || sending) return; setMessages(items => [...items, { role: "user", content: value }]); setQuestion(""); setSending(true); try { const result = await api.ask(value); setMessages(items => [...items, { role: "assistant", content: result.answer, sources: result.citations.map(c => c.customer_name ? `${c.customer_name}: ${c.detail}` : c.detail) }]); } catch (error) { setMessages(items => [...items, { role: "assistant", content: error instanceof Error ? error.message : "I couldn’t answer that." }]); } finally { setSending(false); } };
  const suggestions = ["Which customers should I follow up with today?", "Which opportunities are currently at risk?", "What happened in my last meetings?"];
  return <section className="ask-page"><div className="ask-hero"><span className="ask-star">✦</span><span className="eyebrow">YOUR CRM, EXPLAINED</span><h1>Ask SalesPilot</h1><p>Answers are grounded in the customer records and cite what SalesPilot found.</p></div><div className="chat-thread">{messages.map((message, index) => <div key={index} className={`message ${message.role}`}><span className="message-avatar">{message.role === "assistant" ? "✦" : "AM"}</span><div><div className="message-body">{message.content}</div>{message.sources?.length ? <div className="sources">{message.sources.map(source => <span key={source}>◌ {source}</span>)}</div> : null}</div></div>)}{sending && <div className="message assistant"><span className="message-avatar">✦</span><div className="typing"><i /><i /><i /></div></div>}</div>{messages.length === 1 && <div className="suggestions">{suggestions.map(item => <button key={item} onClick={() => void ask(item)}>{item}<span>→</span></button>)}</div>}<div className="ask-input"><textarea value={question} onChange={e => setQuestion(e.target.value)} onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); void ask(); } }} placeholder="Ask about your customers, meetings, or pipeline…" /><button onClick={() => void ask()} disabled={!question.trim() || sending}>↑</button><small>SalesPilot only uses records available in your CRM.</small></div></section>; }
